
source "amazon-ebs" "autogenerated_1" {
  access_key    = ""
  ami_name      = "cloudknowledge-emi"
  instance_type = "t2.micro"
  region        = "ap-south-1"
  secret_key    = ""
  source_ami    = "ami-0bcf5425cdc1d8a85"
  ssh_username  = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

}
